version: '3'
services:
  flask-app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=likes_db

  redis:
    image: redis:6
    ports:
      - '6379:6379'
