version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: like-microservice
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/likes_db
    depends_on:
      - flask_db
      - redis
  flask_db:
    container_name: flask_db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=likes_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:6.2.4
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  pgdata: {}
  redisdata: {}